# Generated by Django 5.2.5 on 2025-09-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField()),
                ('car_model', models.CharField()),
                ('car_colour', models.CharField()),
                ('car_fc', models.DateField()),
                ('car_manufacturedate', models.DateField()),
                ('car_fueltype', models.CharField()),
            ],
        ),
    ]
